zookeeper:
  address: [127.0.0.1:22181,127.0.0.2:22181]
  root: /pegasus-cluster
  timeout: 1000 # ms
  table_watcher_cache_capacity: 1024

metric:
  type: falcon
  tags: [region=local_tst,service=meta_proxy]
